task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 16G

docker_builder:
  timeout_in: 120m
  env:
    DOCKER_USERNAME: ENCRYPTED[968414e951e41557bf44c6771af7f741be60b7a9c7bf928312426a56ddd929b2ea7b680fb167a75e077bd6d97c08c4c3]
    DOCKER_PASSWORD: ENCRYPTED[9d88c5fccb7243974e55c2de8d0d9adeee91228c71102c4ad1c239c0087bc3eb72ebfb66c5094a20d127befed69259ca]
  docker_builder:
  setup_script:
     - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
     - docker buildx create --name multiarch --driver docker-container --use
     - docker buildx inspect --bootstrap
#    - docker buildx create --name multibuilder
#    - docker buildx use multibuilder
#    - docker buildx inspect --bootstrap
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
 
  build_script: docker buildx build --platform linux/arm64 --file Build/Docker/arm.Dockerfile --tag $DOCKER_USERNAME/arm-bento:latest . --push
  always:
    upload_results_artifacts:
      path: /opt/Bento4/*
      
  push_script: |
           docker push $DOCKER_USERNAME/arm-bento:latest
